"""
Baseline 5: Zero-shot LLM Prompting for recursive generation depth estimation.

Uses an LLM (Claude or OpenAI GPT) to directly judge the recursion depth of a
text passage. No training required — pure in-context prompting.

The prompt explains the concept of recursive text generation and asks the LLM to
classify the text into depth 0 (human-written), 1, 2, or 3 (each successive depth
is generated by an LLM conditioned on the previous depth's output).

Supports: --provider claude (Anthropic API) or --provider openai (OpenAI API)

Input:  Raw depth_*.jsonl files (--data_dirs)
Output: {method}_classification_report.json, {method}_pairwise_auc.json, {method}_predictions.json

Usage:
  python baseline_zeroshot_llm.py --data_dirs data/ --provider claude --max_samples 200
  python baseline_zeroshot_llm.py --data_dirs data/ --provider openai --model gpt-4o
"""

import argparse
import json
import os
import re
import time
import numpy as np
from collections import Counter

from baseline_utils import (
    load_jsonl_data, stratified_split, evaluate_and_save,
    add_common_args, NUM_DEPTHS,
)

SYSTEM_PROMPT = """You are an expert at detecting AI-generated text and estimating its generation depth.

"Recursive generation depth" refers to how many times a text has been through an LLM generation cycle:
- Depth 0: Original human-written text (e.g., Wikipedia, StackExchange, academic papers)
- Depth 1: Text generated by an LLM given human-written text as a prompt/seed
- Depth 2: Text generated by an LLM given depth-1 text as input
- Depth 3: Text generated by an LLM given depth-2 text as input

Key patterns by depth:
- Depth 0 (human): Rich vocabulary, domain-specific terminology, natural topic shifts, occasional typos/informal phrasing
- Depth 1 (first-gen): Fluent but slightly generic, may have formulaic transitions, maintains topic coherence
- Depth 2 (second-gen): More repetitive phrasing, narrower vocabulary, increasingly generic content, possible topic drift
- Depth 3 (third-gen): Noticeable repetition, formulaic structure, may contain subtle incoherence or circular reasoning, very generic language"""

USER_PROMPT_TEMPLATE = """Analyze the following text and estimate its recursive generation depth (0, 1, 2, or 3).

TEXT:
{text}

Respond with ONLY a JSON object in this exact format:
{{"depth": <integer 0-3>, "confidence": <float 0-1>, "reasoning": "<brief one-sentence explanation>"}}"""


def truncate_text(text, max_tokens=512):
    words = text.split()
    approx_tokens = int(max_tokens * 0.75)
    if len(words) > approx_tokens:
        words = words[:approx_tokens]
    return " ".join(words)


def parse_llm_response(response_text):
    """Extract depth prediction from LLM response."""
    json_match = re.search(r'\{[^{}]*"depth"\s*:\s*(\d)[^{}]*\}', response_text)
    if json_match:
        try:
            obj = json.loads(json_match.group(0))
            depth = int(obj.get("depth", -1))
            confidence = float(obj.get("confidence", 0.5))
            if 0 <= depth <= 3:
                return depth, confidence
        except (json.JSONDecodeError, ValueError):
            pass

    digit_match = re.search(r'\b([0-3])\b', response_text)
    if digit_match:
        return int(digit_match.group(1)), 0.5

    return 0, 0.0


def call_claude(text, model, max_tokens=256):
    import anthropic
    client = anthropic.Anthropic()
    message = client.messages.create(
        model=model,
        max_tokens=max_tokens,
        system=SYSTEM_PROMPT,
        messages=[{"role": "user", "content": USER_PROMPT_TEMPLATE.format(text=text)}],
    )
    return message.content[0].text


def call_openai(text, model, max_tokens=256):
    import openai
    client = openai.OpenAI()
    response = client.chat.completions.create(
        model=model,
        max_tokens=max_tokens,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": USER_PROMPT_TEMPLATE.format(text=text)},
        ],
    )
    return response.choices[0].message.content


def main():
    parser = argparse.ArgumentParser(description="Zero-shot LLM Prompting baseline")
    add_common_args(parser)
    parser.add_argument("--provider", choices=["claude", "openai"], default="claude")
    parser.add_argument("--model", default=None,
                        help="Model name (default: claude-sonnet-4-20250514 / gpt-4o)")
    parser.add_argument("--max_eval_samples", type=int, default=200,
                        help="Max samples to evaluate (API cost control)")
    parser.add_argument("--rate_limit_delay", type=float, default=0.5,
                        help="Seconds between API calls")
    args = parser.parse_args()

    if args.model is None:
        args.model = "claude-sonnet-4-20250514" if args.provider == "claude" else "gpt-4o"

    texts, labels = load_jsonl_data(args.data_dirs, max_samples=args.max_samples, seed=args.seed)

    _, eval_idx = stratified_split(labels, eval_split=args.eval_split, seed=args.seed)
    eval_texts = [texts[i] for i in eval_idx]
    eval_labels = labels[eval_idx]

    if len(eval_texts) > args.max_eval_samples:
        rng = np.random.RandomState(args.seed)
        sample_idx = sorted(rng.choice(len(eval_texts), args.max_eval_samples, replace=False))
        eval_texts = [eval_texts[i] for i in sample_idx]
        eval_labels = eval_labels[sample_idx]

    print(f"Evaluating {len(eval_texts)} samples with {args.provider}/{args.model}")
    print(f"Label distribution: {dict(Counter(eval_labels))}")

    call_fn = call_claude if args.provider == "claude" else call_openai
    y_preds, y_probs = [], []
    errors = 0

    for i, (text, label) in enumerate(zip(eval_texts, eval_labels)):
        truncated = truncate_text(text, max_tokens=args.max_seq_len)
        try:
            response = call_fn(truncated, args.model)
            depth, confidence = parse_llm_response(response)
            y_preds.append(depth)
            prob = np.zeros(NUM_DEPTHS)
            prob[depth] = confidence
            remaining = (1.0 - confidence) / max(NUM_DEPTHS - 1, 1)
            for d in range(NUM_DEPTHS):
                if d != depth:
                    prob[d] = remaining
            y_probs.append(prob)
        except Exception as e:
            print(f"  [{i}] API error: {e}")
            y_preds.append(0)
            y_probs.append(np.ones(NUM_DEPTHS) / NUM_DEPTHS)
            errors += 1

        if (i + 1) % 20 == 0:
            print(f"  Progress: {i+1}/{len(eval_texts)}")

        if args.rate_limit_delay > 0:
            time.sleep(args.rate_limit_delay)

    y_preds = np.array(y_preds)
    y_probs = np.array(y_probs)

    if errors > 0:
        print(f"\n{errors}/{len(eval_texts)} API errors encountered.")

    method_name = f"zeroshot_{args.provider}_{args.model.replace('/', '_')}"
    evaluate_and_save(method_name, eval_labels, y_preds, y_probs, args.output_dir)


if __name__ == "__main__":
    main()
