"""
Baseline: Zero-shot LLM Prompting for recursive generation depth estimation.

Uses an LLM (Claude or OpenAI GPT) to directly judge the recursion depth of a
text passage via in-context prompting. No training required.

The prompt explains recursive generation and asks the LLM to classify text into
depth 0 (human-written), 1 (first-gen), 2 (second-gen), or 3 (third-gen).

Evaluates both 4-class (depth 0-3) and 3-class (depth 1-3, generated text only).

Input:  Raw depth_*.jsonl files (--data_dirs)
Output: {method}_classification_report.json, {method}_pairwise_auc.json, {method}_predictions.json

Dependencies: anthropic (for Claude), openai (for GPT)
API keys: ANTHROPIC_API_KEY or OPENAI_API_KEY environment variable

Usage:
  python baseline_zero_shot_llm.py --data_dirs data/ --provider claude --max_eval_samples 200
  python baseline_zero_shot_llm.py --data_dirs data/ --provider openai --model gpt-4o
  python baseline_zero_shot_llm.py --data_dirs data/ --provider claude --dry_run
"""

import argparse
import json
import os
import re
import time
import glob as glob_mod
import numpy as np
from collections import Counter

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, roc_auc_score

NUM_DEPTHS = 4
DEPTH_LABELS = list(range(NUM_DEPTHS))

SYSTEM_PROMPT = """You are an expert at detecting AI-generated text and estimating its generation depth.

"Recursive generation depth" refers to how many times a text has been through an LLM generation cycle:
- Depth 0: Original human-written text (e.g., Wikipedia, StackExchange, academic papers)
- Depth 1: Text generated by an LLM given human-written text as a prompt/seed
- Depth 2: Text generated by an LLM given depth-1 text as input
- Depth 3: Text generated by an LLM given depth-2 text as input

Key patterns by depth:
- Depth 0 (human): Rich vocabulary, domain-specific terminology, natural topic shifts, occasional typos/informal phrasing
- Depth 1 (first-gen): Fluent but slightly generic, may have formulaic transitions, maintains topic coherence
- Depth 2 (second-gen): More repetitive phrasing, narrower vocabulary, increasingly generic content, possible topic drift
- Depth 3 (third-gen): Noticeable repetition, formulaic structure, may contain subtle incoherence or circular reasoning, very generic language"""

USER_PROMPT_TEMPLATE = """Analyze the following text and estimate its recursive generation depth (0, 1, 2, or 3).

TEXT:
{text}

Respond with ONLY a JSON object in this exact format:
{{"depth": <integer 0-3>, "confidence": <float 0-1>, "reasoning": "<brief one-sentence explanation>"}}"""


def load_jsonl_data(data_dirs, max_samples=0, seed=42):
    texts, labels = [], []
    for data_dir in data_dirs:
        for d in range(NUM_DEPTHS):
            fpath = os.path.join(data_dir, f"depth_{d}.jsonl")
            if not os.path.exists(fpath):
                matches = glob_mod.glob(os.path.join(data_dir, f"*depth_{d}*.jsonl"))
                fpath = matches[0] if matches else None
            if fpath is None or not os.path.exists(fpath):
                continue
            with open(fpath) as f:
                for line in f:
                    line = line.strip()
                    if not line:
                        continue
                    rec = json.loads(line)
                    texts.append(rec["text"])
                    labels.append(rec.get("depth", d))
    labels = np.array(labels, dtype=np.int64)
    if max_samples > 0 and len(texts) > max_samples:
        rng = np.random.RandomState(seed)
        idx = sorted(rng.choice(len(texts), max_samples, replace=False))
        texts = [texts[i] for i in idx]
        labels = labels[idx]
    print(f"Loaded {len(texts)} samples. Depth distribution: {dict(Counter(labels))}")
    return texts, labels


def stratified_split(labels, eval_split=0.15, seed=42):
    train_idx, eval_idx = train_test_split(
        np.arange(len(labels)), test_size=eval_split,
        stratify=labels, random_state=seed,
    )
    return train_idx, eval_idx


def pairwise_auc(y_true, y_prob, d1, d2):
    mask = np.isin(y_true, [d1, d2])
    if mask.sum() < 2:
        return None
    yt = (y_true[mask] == d2).astype(int)
    if len(np.unique(yt)) < 2:
        return None
    yp = y_prob[mask, d2]
    return float(roc_auc_score(yt, yp))


def compute_all_pairwise_auc(y_true, y_prob, depth_labels):
    result = {}
    for i, d1 in enumerate(depth_labels):
        for d2 in depth_labels[i + 1:]:
            auc = pairwise_auc(y_true, y_prob, d1, d2)
            result[f"d{d1}_vs_d{d2}"] = round(auc, 4) if auc is not None else None
    return result


def bootstrap_ci(y_true, y_pred, n_boot=1000, seed=42):
    rng = np.random.RandomState(seed)
    scores = []
    n = len(y_true)
    for _ in range(n_boot):
        idx = rng.choice(n, n, replace=True)
        scores.append(accuracy_score(y_true[idx], y_pred[idx]))
    return float(np.percentile(scores, 2.5)), float(np.percentile(scores, 97.5))


def evaluate_and_save(method_name, y_true, y_pred, y_prob, output_dir):
    os.makedirs(output_dir, exist_ok=True)
    y_true = np.asarray(y_true)
    y_pred = np.asarray(y_pred)

    acc4 = accuracy_score(y_true, y_pred)
    ci_lo, ci_hi = bootstrap_ci(y_true, y_pred)
    mae = float(np.mean(np.abs(y_true - y_pred)))

    mask_gen = y_true >= 1
    acc3 = accuracy_score(y_true[mask_gen], y_pred[mask_gen]) if mask_gen.sum() > 0 else 0.0

    pair_aucs_4 = compute_all_pairwise_auc(y_true, y_prob, DEPTH_LABELS) if y_prob is not None else {}
    pair_aucs_3 = compute_all_pairwise_auc(
        y_true[mask_gen], y_prob[mask_gen], [1, 2, 3]
    ) if y_prob is not None and mask_gen.sum() > 0 else {}

    cr_4class = classification_report(
        y_true, y_pred,
        target_names=[f"d{d}" for d in DEPTH_LABELS],
        output_dict=True, zero_division=0,
    )
    cr_3class = {}
    if mask_gen.sum() > 0:
        cr_3class = classification_report(
            y_true[mask_gen], y_pred[mask_gen],
            labels=[1, 2, 3],
            target_names=["d1", "d2", "d3"],
            output_dict=True, zero_division=0,
        )

    print(f"\n{'=' * 60}")
    print(f"  {method_name}")
    print(f"{'=' * 60}")
    print(f"  4-class accuracy : {acc4:.4f}  (95% CI: [{ci_lo:.4f}, {ci_hi:.4f}])")
    print(f"  3-class accuracy : {acc3:.4f}  (d1-d3 only)")
    print(f"  MAE              : {mae:.4f}")
    print(f"  4-class AUC      : {pair_aucs_4}")
    print(f"  3-class AUC      : {pair_aucs_3}")
    print(classification_report(
        y_true, y_pred,
        target_names=[f"d{d}" for d in DEPTH_LABELS], zero_division=0,
    ))

    report = {
        "accuracy_4class": round(acc4, 4),
        "accuracy_4class_ci": [round(ci_lo, 4), round(ci_hi, 4)],
        "accuracy_3class": round(acc3, 4),
        "mae": round(mae, 4),
        "pairwise_auc_4class": pair_aucs_4,
        "pairwise_auc_3class": pair_aucs_3,
        "per_class_4class": cr_4class,
        "per_class_3class": cr_3class,
    }
    _save_json(os.path.join(output_dir, f"{method_name}_classification_report.json"), report)
    _save_json(os.path.join(output_dir, f"{method_name}_pairwise_auc.json"),
               {"4class": pair_aucs_4, "3class": pair_aucs_3})

    preds = []
    for i in range(len(y_true)):
        entry = {"y_true": int(y_true[i]), "y_pred": int(y_pred[i])}
        if y_prob is not None:
            entry["y_prob"] = [round(float(p), 6) for p in y_prob[i]]
        preds.append(entry)
    _save_json(os.path.join(output_dir, f"{method_name}_predictions.json"), preds)

    print(f"  Saved to {output_dir}/")
    return {"accuracy_4class": acc4, "accuracy_3class": acc3, "mae": mae}


def _save_json(path, obj):
    with open(path, "w") as f:
        json.dump(obj, f, indent=2)


def truncate_text(text, max_tokens=512):
    words = text.split()
    approx_tokens = int(max_tokens * 0.75)
    if len(words) > approx_tokens:
        words = words[:approx_tokens]
    return " ".join(words)


def parse_llm_response(response_text):
    json_match = re.search(r'\{[^{}]*"depth"\s*:\s*(\d)[^{}]*\}', response_text)
    if json_match:
        try:
            obj = json.loads(json_match.group(0))
            depth = int(obj.get("depth", -1))
            confidence = float(obj.get("confidence", 0.5))
            if 0 <= depth <= 3:
                return depth, confidence
        except (json.JSONDecodeError, ValueError):
            pass

    digit_match = re.search(r'\b([0-3])\b', response_text)
    if digit_match:
        return int(digit_match.group(1)), 0.5

    return 0, 0.0


def call_claude(text, model, max_tokens=256):
    """Requires ANTHROPIC_API_KEY environment variable."""
    import anthropic
    client = anthropic.Anthropic()  # uses ANTHROPIC_API_KEY env var
    message = client.messages.create(
        model=model,
        max_tokens=max_tokens,
        system=SYSTEM_PROMPT,
        messages=[{"role": "user", "content": USER_PROMPT_TEMPLATE.format(text=text)}],
    )
    return message.content[0].text


def call_openai(text, model, max_tokens=256):
    """Requires OPENAI_API_KEY environment variable."""
    import openai
    client = openai.OpenAI()  # uses OPENAI_API_KEY env var
    response = client.chat.completions.create(
        model=model,
        max_tokens=max_tokens,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": USER_PROMPT_TEMPLATE.format(text=text)},
        ],
    )
    return response.choices[0].message.content


def main():
    parser = argparse.ArgumentParser(description="Zero-shot LLM Prompting baseline")
    parser.add_argument("--data_dirs", nargs="+", default=["data/"])
    parser.add_argument("--output_dir", default="results/baselines/")
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--eval_split", type=float, default=0.15)
    parser.add_argument("--max_samples", type=int, default=0)
    parser.add_argument("--max_seq_len", type=int, default=512)
    parser.add_argument("--provider", choices=["claude", "openai"], default="claude")
    parser.add_argument("--model", default=None,
                        help="Model name (default: claude-sonnet-4-20250514 / gpt-4o)")
    parser.add_argument("--max_eval_samples", type=int, default=200,
                        help="Max samples to evaluate (API cost control)")
    parser.add_argument("--rate_limit_delay", type=float, default=0.5,
                        help="Seconds between API calls")
    parser.add_argument("--dry_run", action="store_true",
                        help="Process only 5 samples for testing")
    args = parser.parse_args()

    if args.model is None:
        args.model = "claude-sonnet-4-20250514" if args.provider == "claude" else "gpt-4o"

    api_key_var = "ANTHROPIC_API_KEY" if args.provider == "claude" else "OPENAI_API_KEY"
    if not os.environ.get(api_key_var):
        print(f"ERROR: {api_key_var} environment variable not set.")
        print(f"Set it with: export {api_key_var}=your_key_here")
        return

    texts, labels = load_jsonl_data(args.data_dirs, max_samples=args.max_samples, seed=args.seed)

    _, eval_idx = stratified_split(labels, eval_split=args.eval_split, seed=args.seed)
    eval_texts = [texts[i] for i in eval_idx]
    eval_labels = labels[eval_idx]

    if args.dry_run:
        eval_texts = eval_texts[:5]
        eval_labels = eval_labels[:5]
    elif len(eval_texts) > args.max_eval_samples:
        rng = np.random.RandomState(args.seed)
        sample_idx = sorted(rng.choice(len(eval_texts), args.max_eval_samples, replace=False))
        eval_texts = [eval_texts[i] for i in sample_idx]
        eval_labels = eval_labels[sample_idx]

    print(f"Evaluating {len(eval_texts)} samples with {args.provider}/{args.model}")
    print(f"Label distribution: {dict(Counter(eval_labels))}")

    call_fn = call_claude if args.provider == "claude" else call_openai
    y_preds, y_probs = [], []
    errors = 0

    for i, (text, label) in enumerate(zip(eval_texts, eval_labels)):
        truncated = truncate_text(text, max_tokens=args.max_seq_len)
        try:
            response = call_fn(truncated, args.model)
            depth, confidence = parse_llm_response(response)
            y_preds.append(depth)
            prob = np.zeros(NUM_DEPTHS)
            prob[depth] = confidence
            remaining = (1.0 - confidence) / max(NUM_DEPTHS - 1, 1)
            for d in range(NUM_DEPTHS):
                if d != depth:
                    prob[d] = remaining
            y_probs.append(prob)
        except Exception as e:
            print(f"  [{i}] API error: {e}")
            y_preds.append(0)
            y_probs.append(np.ones(NUM_DEPTHS) / NUM_DEPTHS)
            errors += 1

        if (i + 1) % 20 == 0:
            print(f"  Progress: {i+1}/{len(eval_texts)}")

        if args.rate_limit_delay > 0:
            time.sleep(args.rate_limit_delay)

    y_preds = np.array(y_preds)
    y_probs = np.array(y_probs)

    if errors > 0:
        print(f"\n{errors}/{len(eval_texts)} API errors encountered.")

    model_tag = args.model.replace("/", "_").replace("-", "_")
    method_name = f"zeroshot_{args.provider}_{model_tag}"
    evaluate_and_save(method_name, eval_labels, y_preds, y_probs, args.output_dir)


if __name__ == "__main__":
    main()
